# This file tells Binder to build a Conda environment
name: fenics-environment

# We use the conda-forge channel, which is the standard for scientific packages
channels:
  - conda-forge

# List of packages to install. Binder will automatically run this with Conda.
dependencies:
  - python=3.9
  - fenics
  - matplotlib
  - numpy
  - plotly # <-- Add this line
  - scipy # <-- Add this line
  - pillow
  - notebook
  - zip   # <-- Add this line
  - tar   # <-- Add this line too (good practice)
